=== jxb8901/uc/mars/src/venus.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--

1、强制使用一个交易类包括多个action的方式
2、交易类的类名及位置使用固定的规则映射
3、Result使用固定的类型，location使用固定的映射方式
4、interceptor使用默认配置，允许覆盖？
5、exceptionMapping？
6、数据验证器配置？
7、数据类型转换？
8、交易相关的action要不要强制声明？
9、支持交易继承?，可选择继承项(处理类、目标JSP、等等)
		可继承项：transactionClass, resultView, 可针对action进行更细粒度的控制
		input,output,expression: 如果未声明子元素，可声明是否继承，如果已声明子元素，则使用merge选项继承
		interceptor的继承:
10、支持WW的param
11、可以在这里定义message

12、help支持

13、oneclass模式？：class属性改名为oneclass或其它更有意义的名称

14、查询字段、引用字段、字段包含与排斥

15、模型字段

16、两类交易：
	A、数据库类交易（CRUD和Query），提供支持：
		页面数据验证
		数据类型转换（页面的字符串数据转换为entity对象）
		页面生成（数据录入页面、查询结果页面）
		不需要写webwork的action
	B、报文类交易

17、交易链：
	暂时未实现交易链，可考虑通过以下方式支持：
	A、通过配置文件中配置chainresult来实现
	B、通过检查结果代码是否已特定前缀开始（如：以chain:开头的结果码认为是链接交易）

18、static-params应该比params后执行，以免客户端数据覆盖设置

字段配置信息的用途：
	公共信息：名称、action
	用于验证：中文名、数据类型、maxlen,maxvalue,...
	用于生成查询条件：实际名称、比较操作符
	用于生成页面：同验证的信息

TODO: 检查包同名！


-->

<!ENTITY % NAMES  "
    name CDATA #REQUIRED
    cname CDATA #IMPLIED
">

<!ENTITY % ACTION  "
    action CDATA #IMPLIED
">

<!--
注意：下面的DTD声明中不能使用默认值，否则会影响FieldConfImpl中的merge的形为
因为根据Dom4j的API无法判断某个属性是用户明确设置的还是通过DTD中的默认值设置的
-->
<!ENTITY % FIELDATTR  "
	%ACTION;
	converter CDATA #IMPLIED
	maxlen CDATA #IMPLIED
	maxvalue CDATA #IMPLIED
	minlen CDATA #IMPLIED
	minvalue CDATA #IMPLIED
	key (true | false) #IMPLIED
	req (true | false) #IMPLIED
	len CDATA #IMPLIED
	type (string | bool | date | amount | integer | url | email | password) #IMPLIED
	tagtype ( auto | textfield | textarea | hidden | pre | select | radio | checkbox | text | file | img ) #IMPLIED
	pattern CDATA #IMPLIED
	jspattern CDATA #IMPLIED
	patternmsg CDATA #IMPLIED
">
 
 <!-- document definition -->

<!ELEMENT venus (package | include)*>
<!ATTLIST venus
    appname CDATA #IMPLIED
    appcname CDATA #IMPLIED
    controllerbasedir CDATA #IMPLIED
    viewbasedir CDATA #IMPLIED
>

<!ELEMENT include EMPTY>
<!ATTLIST include
    file CDATA #REQUIRED
>

<!--
	class: [@deprecated]表示本包中的Transaction共用同一个以包名为名称的类
				用于实现CRUD操作共用同一个交易类
-->
<!ELEMENT package (model | package | transaction)*>
<!ATTLIST package
    %NAMES;
    class (true | false) 'false'
>

<!--
	inherit: 可包含all或以下值的组合：class, result, validators
					注意默认情况下result是不继承的
	type: 交易类型，query表示查询交易，目前对此类交易有特别支持
			查询交易的input元素中只能出现查询字段queryfield
-->
<!ELEMENT transaction (param*, input?, output?, expressions?)>
<!ATTLIST transaction
    %NAMES;
    extend CDATA #IMPLIED
    inherit CDATA "  class,  validator  "
    abstract CDATA #IMPLIED
    interceptors CDATA #IMPLIED
	type ( query | view | create | update | delete | reflect | xwork ) #IMPLIED
>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param
	%NAMES;
	value CDATA #IMPLIED
>

<!--
	entity: 指示相应的实体类名称，目前填写实体类的类名，
		该名称一般与hibernate的hbm文件中的名称一致
		对于查询类交易，该属性必填
-->
<!ELEMENT model ( field | modelfields | enumfield)+ >
<!ATTLIST model
    entity CDATA #IMPLIED
    class CDATA #IMPLIED
>
<!ELEMENT input ( field | mergefield | includefields | excludefields | queryfield | modelfields )* >
<!ELEMENT output ( field | mergefield | includefields | excludefields )* >

<!--
	元素内容为需要引入的字段名，字段间用逗号隔开
-->
<!ELEMENT modelfields (#PCDATA)>
<!ATTLIST modelfields
	%NAMES;
	model CDATA #REQUIRED
	multi (true | false) 'false'
	%FIELDATTR;
>
<!ELEMENT enumfield (#PCDATA)>
<!ATTLIST enumfield
	%NAMES;
	enum CDATA #IMPLIED
	multi (true | false) 'false'
	elementtype CDATA #IMPLIED
	%FIELDATTR;
>
<!--
	元素内容为需要包含的字段名，字段间用逗号隔开
-->
<!ELEMENT includefields (#PCDATA)>
<!ATTLIST includefields
	%FIELDATTR;
>
<!--
	元素内容为不包含的字段名，字段间用逗号隔开
-->
<!ELEMENT excludefields (#PCDATA)>
<!ATTLIST excludefields
	%FIELDATTR;
>
<!ELEMENT mergefield (#PCDATA)>
<!ATTLIST mergefield
	%NAMES;
	%FIELDATTR;
>

<!--
	op: 查询时的比较运算符
-->
<!ELEMENT queryfield (#PCDATA)>
<!ATTLIST queryfield
	%NAMES;
	op ( eq | ne | gt | ge | lt | le | like | between ) #REQUIRED
	%FIELDATTR;
>

<!--

	action：控制检验所应用的动作，可用如下格式取值：
			"" - 不填或为空，表示检验应用于除默认动作以外的所有动作
			"any" - 表示检验应用于所有动作
			action ("," action)* - action为动作名，表示检验应用于所列出的动作
			
	TODO: password类型的验证器需要订制
-->
<!ELEMENT field (#PCDATA)>
<!ATTLIST field
	%NAMES;
	%FIELDATTR;
>

<!ELEMENT expressions (expression+)>
<!ATTLIST expressions
	%ACTION;
>

<!--
	TODO: depends未实现
-->
<!ELEMENT expression (java?, javascript?)>
<!ATTLIST expression
	%NAMES;
	fieldname CDATA #IMPLIED
	action CDATA #IMPLIED
	depends CDATA #IMPLIED
	errormsg CDATA #REQUIRED
>
<!ELEMENT java (#PCDATA)>
<!ELEMENT javascript (#PCDATA)>

=== jxb8901/uc/venus/conf/trans/venus.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE venus PUBLIC 
		"-//ninecube//venus1.0//EN" 
		"http://www.ninecube.net/venus/venus.dtd">

<venus appname="venus" appcname="积分营销系统" controllerbasedir="net.ninecube.test.trans" viewbasedir="/WEB-INF/views">

	<include file="venus.system.xml"/>
	
	<include file="venus.customergroup.xml"/>
	
	<include file="venus.promotionplan.xml"/>
	
	<include file="venus.evaluation.xml"/>
	
	<include file="venus.metric.xml"/>
	
	<include file="venus.ruleentity.xml"/>
	
	<include file="venus.gift.xml"/>
	
	<include file="venus.customer.xml"/>
	
	<include file="venus.user.xml"/>
	
	<include file="venus.test.xml"/>
	
	<include file="venus.report.xml"/>
	
	<include file="venus.manage.xml"/>
	
</venus>

=== jxb8901/uc/venus/conf/trans/venus.manage.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE venus PUBLIC 
		"-//ninecube//venus1.0//EN" 
		"http://www.ninecube.net/venus/venus.dtd">

<venus>
	
	<package name="task" cname="系统管理" >
		<package name="definition" cname="任务管理" >
			<model entity="taskDefinition" class="net.ninecube.core.task.TaskDefinition">
				<field name="idno" cname="ID" key="true" />
				<field name="name" cname="名称" />
				<field name="group" cname="组" />
				<field name="description" cname="描述" />
			</model>
			<transaction name="getTasks" cname="任务列表" type="reflect" >
			</transaction>
			<transaction name="run" cname="执行任务" />
		</package>
		<package name="status" cname="任务调度" >
			<model entity="taskStatus" class="net.ninecube.core.task.TaskStatus">
				<field name="idno" cname="ID" key="true" />
				<modelfields name="detail" cname="任务定义" model="taskDefinition">name</modelfields>
				<field name="startDateTime" cname="开始时间" />
				<field name="status" cname="运行状态" />
			</model>
			<transaction name="getExecutingTasks" cname="任务调度" type="reflect" >
			</transaction>
		</package>
	</package>
	
</venus>

=== jxb8901/uc/mars/test/venus-test.user.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE venus PUBLIC 
		"-//ninecube//venus1.0//EN" 
		"http://www.ninecube.net/venus/venus.dtd">

<venus>
	
	<package name="manage" cname="系统管理"  >
		<package name="user" cname="用户管理"  >
			<model class="net.ninecube.test.domain.TestUser" entity="testuser">
				<field name="idno" converter="" cname="ID" type="integer" key="true"/>
				<field name="userid" converter="" cname="用户ID" type="integer" />
				<field name="name" converter="" cname="名称" maxlen="20" minlen="6" />
				<field name="creationDate" cname="描述" type="date" maxlen="255" />
				<field name="amount" cname="金额" type="amount" maxvalue="99999" minvalue="0"/>
				<field name="password" cname="密码" maxlen="6" />
				<field name="password2" cname="确认密码" maxlen="6" />
				<field name="staticParam" cname="静态参数">120</field>
				<enumfield name="role" cname="角色" enum="角色" />
			</model>
			
			<transaction name="query" cname="用户查询" >
				<input>
					<queryfield name="name" op="like" />
					<queryfield name="creationDate" op="between" />
					<queryfield name="password" op="eq" />
					<queryfield name="amount" op="gt" />
					<field name="flag" cname="标志">${user.field}</field>
				</input>
				<output>
					<includefields tagtype="text">*</includefields>
					<mergefield name="idno" tagtype="radio" />
				</output>
			</transaction>
			<transaction name="read" cname="查看" >
				<input>
					<includefields>idno</includefields>
				</input>
			</transaction>
			<transaction name="edit" cname="修改用户" >
				<input>
				</input>
				<expressions>
					<expression name="exp1" errormsg="密码与确认密码不符" depends="Password,Password2">
						<java>password == password2</java>
						<javascript>$("Password").value == document.forms[0].Password2.value</javascript>
					</expression>
				</expressions>
			</transaction>
			<transaction name="add" cname="修改用户" extend="edit" />
			<transaction name="create" cname="新增用户" >
				<input>
					<includefields>*</includefields>
					<mergefield name="idno" req="true" tagtype="hidden" />
				</input>
			</transaction>
			<transaction name="delete" cname="删除用户" >
				<input>
					<includefields>userid</includefields>
				</input>
			</transaction>
			<transaction name="testMerge" cname="测试字段合并用的交易" >
				<input>
					<mergefield name="idno" req="true" tagtype="hidden" type="date"/>
					<mergefield name="userid" />
				</input>
			</transaction>
		</package>
		
		<package name="userManage" cname="用户管理" >
			<transaction name="list" cname="查询" />
			<transaction name="view" cname="查看" />
			<transaction name="save" cname="保存" />
			<transaction name="delete" cname="删除" />
		</package>
	</package>
</venus>

=== jxb8901/uc/venus/conf/trans/venus.gift.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE venus PUBLIC 
		"-//ninecube//venus1.0//EN" 
		"http://www.ninecube.net/venus/venus.dtd">

<venus>
	
	<package name="gift" cname="礼品管理" >
		<package name="gift" cname="礼品库" >
			<model entity="gift" class="net.ninecube.venus.domain.Gift">
				<field name="idno" cname="ID" key="true" />
				<field name="seqno" cname="编号" req="true" />
				<field name="name" cname="名称" req="true" />
				<field name="image" cname="图片" tagtype="file" />
				<field name="marketPrice" cname="市场价格" />
				<field name="costPrice" cname="成本价格" />
				<field name="availableQuantity" cname="可用数量" />
				<field name="exchangeRule" cname="兑换规则" />
				<field name="description" cname="描述" />
			</model>
			<transaction name="query" cname="查询" >
				<input>
					<queryfield name="name" op="like" />
					<queryfield name="marketPrice" op="between" />
					<queryfield name="availableQuantity" op="between" />
				</input>
				<output>
					<includefields tagtype="text">*</includefields>
					<mergefield name="idno" tagtype="radio" />
					<mergefield name="image" tagtype="img" />
				</output>
			</transaction>
			<transaction name="read" cname="查看" />
			<transaction name="create" cname="新建" />
			<transaction name="update" cname="修改" />
			<transaction name="delete" cname="删除" />
			<transaction name="download" cname="下载" />
		</package>
		<package name="dispatchinggift" cname="待配送礼品" >
			<model entity="dispatchingGift" class="net.ninecube.venus.domain.DispatchingGift">
				<field name="idno" cname="ID" key="true" />
				<modelfields name="customer" cname="申请客户" model="customer" >customerNo,name</modelfields>
				<modelfields name="gift" cname="礼品" model="gift" >seqno,name</modelfields>
				<field name="quantity" cname="数量" />
				<field name="applyDate" cname="申请日期" >${today}</field>
			</model>
			<transaction name="query" cname="查询" >
				<input>
					<queryfield name="customer.name" op="like" />
					<queryfield name="applyDate" op="between" />
				</input>
				<output>
					<includefields tagtype="radio" >idno</includefields>
					<includefields tagtype="text">customer.customerNo, customer.name, gift.seqno, gift.name</includefields>
					<includefields tagtype="img">gift.image</includefields>
					<includefields tagtype="text">quantity,applyDate</includefields>
				</output>
			</transaction>
			<transaction name="read" cname="查看" />
			<transaction name="create" cname="新建" />
			<transaction name="update" cname="修改" />
			<transaction name="delete" cname="删除" />
		</package>
	</package>
	
</venus>

=== jxb8901/uc/venus/conf/trans/venus.test.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE venus PUBLIC "-//ninecube//venus1.0//EN" "http://www.ninecube.net/venus/venus.dtd">

<venus>

	<package name="test" cname="测试" >
		<model entity="test_student" class="net.ninecube.test.domain.Student">
			<field name="idno" cname="ID" type="integer" key="true" />
			<field name="name" cname="名称" maxlen="20" req="true" />
			<modelfields name="peer" cname="同桌" model="test_student" >name</modelfields>
			<modelfields name="classmate" cname="同学" model="test_student" multi="true" >idno, name</modelfields>
			<enumfield name="mainrole" cname="主要角色" enum="user.role" />
			<enumfield name="roles" cname="角色" enum="user.role" multi="true" />
		</model>

		<transaction name="query" cname="查询" >
			<input>
				<queryfield name="name" op="like" />
			</input>
			<output>
				<includefields tagtype="text">*</includefields>
				<mergefield name="idno" tagtype="radio" />
			</output>
		</transaction>
		
		<transaction name="read" cname="查看" />
		<transaction name="create" cname="新建" />
		<transaction name="update" cname="修改" />
		<transaction name="delete" cname="删除" />
		
	</package>
		
</venus>

=== jxb8901/uc/venus/conf/trans/venus.system.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE venus PUBLIC 
		"-//ninecube//venus1.0//EN" 
		"http://www.ninecube.net/venus/venus.dtd">

<venus controllerbasedir="net.ninecube.core.trans">

	<package name="system" cname="系统功能">
		<transaction name="nothing" cname="不做事的交易" />
		<transaction name="index" cname="" />
		<transaction name="login" cname="登录"  >
			<input>
				<field name="userid" cname="用户ID" req="true"  action="submit"/>
				<field name="password" cname="密码" req="true" len="6"  action="submit"/>
			</input>
		</transaction>
		
		<transaction name="main" cname="main" extend="nothing" />
		<transaction name="top" cname="top" extend="nothing" />
		<transaction name="left" cname="left" extend="nothing" />
		<transaction name="home" cname="home" extend="nothing" />
	</package>
	
</venus>

=== jxb8901/uc/venus/conf/trans/venus.report.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE venus PUBLIC 
		"-//ninecube//venus1.0//EN" 
		"http://www.ninecube.net/venus/venus.dtd">

<venus>
	
	<package name="report" cname="报表管理" >
		<package name="reportDefinition" cname="报表定义管理" >
			<model entity="reportDefinition" class="net.ninecube.reports.objects.Report">
				<field name="idno" cname="ID" key="true" />
				<field name="name" cname="名称" req="true" maxlen="20" />
				<modelfields name="reportChart" cname="图表" model="reportChartDefinition" >name</modelfields>
				<field name="query" cname="查询语句" tagtype="textarea" />
				<!--
				<field name="pdfExportEnabled" cname="PDF" req="true" maxlen="100" />
				<field name="htmlExportEnabled" cname="HTML" req="true" maxlen="100" />
				<field name="csvExportEnabled" cname="CSV" req="true" maxlen="100" />
				<field name="xlsExportEnabled" cname="XLS" req="true" maxlen="100" />
				<field name="rtfExportEnabled" cname="RTF" req="true" maxlen="100" />
				<field name="textExportEnabled" cname="TEXT" req="true" maxlen="100" />
				<field name="excelExportEnabled" cname="EXCEL" req="true" maxlen="100" />
				<field name="virtualizationEnabled" cname="VIRTUALIZATION" req="true" maxlen="100" />
				-->
				<field name="description" cname="描述" maxlen="255"  tagtype="textarea" />
			</model>
			<transaction name="query" cname="查询" >
				<input>
					<queryfield name="name" op="like" />
					<queryfield name="description" op="like" tagtype="textfield" />
				</input>
				<output>
					<includefields tagtype="text">idno,name,description</includefields>
					<mergefield name="idno" tagtype="radio" />
				</output>
			</transaction>
			<transaction name="read" cname="查看" />
			<transaction name="create" cname="新建" />
			<transaction name="update" cname="修改" />
			<transaction name="delete" cname="删除" />
		</package>
		<package name="reportChartDefinition" cname="图表定义管理" >
			<model entity="reportChartDefinition" class="net.ninecube.reports.objects.ReportChart">
				<field name="idno" cname="ID" key="true" />
				<field name="name" cname="名称" req="true" maxlen="20" />
				<field name="query" cname="查询语句" req="true" tagtype="textarea" />
				<enumfield name="chartType" cname="图表类型" enum="report.chart.type" />
				<field name="width" cname="宽度" />
				<field name="height" cname="高度" />
				<field name="xaxisLabel" cname="X轴标题" />
				<field name="yaxisLabel" cname="Y轴标题" />
				<enumfield name="showLegend" cname="是否显示图例" type="bool" />
				<enumfield name="showTitle" cname="是否显示标题" type="bool" />
				<enumfield name="showValues" cname="是否显示值" type="bool" />
				<enumfield name="plotOrientation" cname="方向" enum="report.chart.orientation" />
				<field name="description" cname="描述" maxlen="255" tagtype="textarea" />
			</model>
			<transaction name="query" cname="查询" >
				<input>
					<queryfield name="name" op="like" />
					<queryfield name="description" op="like" tagtype="textfield" />
				</input>
				<output>
					<includefields tagtype="text">idno,name,description</includefields>
					<mergefield name="idno" tagtype="radio" />
				</output>
			</transaction>
			<transaction name="read" cname="查看" />
			<transaction name="create" cname="新建" />
			<transaction name="update" cname="修改" />
			<transaction name="delete" cname="删除" />
		</package>
		<!-- package name="reportTemplate" cname="报表模板管理" >
			<model entity="reportTemplate" class="net.ninecube.report.domain.ReportTemplate">
				<field name="idno" cname="ID" key="true" />
				<field name="name" cname="名称" req="true" maxlen="20" />
				<field name="description" cname="描述" maxlen="255" />
				<field name="content" cname="模板文件" tagtype="file" />
			</model>
			<transaction name="query" cname="查询" >
				<input>
					<queryfield name="name" op="like" />
				</input>
			</transaction>
			<transaction name="read" cname="查看" />
			<transaction name="create" cname="新建" />
			<transaction name="update" cname="修改" />
			<transaction name="delete" cname="删除" />
		</package -->
		<package name="reportParameter" cname="报表参数管理" >
			<model entity="reportParameter" class="net.ninecube.reports.objects.ReportParameter">
				<field name="idno" cname="ID" key="true" />
				<field name="name" cname="名称" req="true" maxlen="20" />
				<enumfield name="type" cname="类型" enum="report.parameter.type"/>
				<enumfield name="className" cname="java class" enum="report.parameter.class" />
				<field name="data" cname="数据" />
				<field name="description" cname="描述" />
				<enumfield name="required" cname="是否必输" type="bool"/>
				<enumfield name="multipleSelect" cname="多选" type="bool"/>
			</model>
			<transaction name="query" cname="查询" >
				<input>
					<queryfield name="name" op="like" />
				</input>
				<output>
					<includefields tagtype="text">idno, name, type, description</includefields>
					<mergefield name="idno" tagtype="radio" />
				</output>
			</transaction>
			<transaction name="read" cname="查看" />
			<transaction name="create" cname="新建" />
			<transaction name="update" cname="修改" />
			<transaction name="delete" cname="删除" />
		</package>
	</package>
	
</venus>

=== jxb8901/uc/venus/conf/trans/venus.customergroup.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE venus PUBLIC "-//ninecube//venus1.0//EN" "http://www.ninecube.net/venus/venus.dtd">

<venus>

	<package name="customergroup" cname="客户群管理" >
		<model entity="customergroup" class="net.ninecube.venus.domain.CustomerGroup">
			<field name="idno" cname="ID" type="integer" key="true" />
			<field name="name" cname="名称" maxlen="20" req="true" />
			<modelfields name="parent" cname="上级客户群" model="customergroup" >name</modelfields>
			<field name="rule" cname="划分规则" maxlen="255" req="true" />
			<field name="description" cname="描述" maxlen="255" />
			<modelfields name="evaluation" cname="评价体系" model="evaluation" req="true">name</modelfields>
			<field name="creationDate" cname="创建日期" type="date" >${today}</field>
			<field name="creator" cname="创建人" >${user.name}</field>
		</model>

		<transaction name="query" cname="查询" >
			<input>
				<queryfield name="name" op="like" />
				<queryfield name="creationDate" op="between" />
				<queryfield name="creator" op="eq" />
			</input>
			<output>
				<includefields tagtype="text">*</includefields>
				<mergefield name="idno" tagtype="radio" />
			</output>
		</transaction>
		
		<transaction name="read" cname="查看" />
		<transaction name="create" cname="新建" />
		<transaction name="update" cname="修改" />
		<transaction name="delete" cname="删除" />
		
		<transaction name="eval" cname="评价" >
			<input>
				<modelfields name="customerGroup" cname="客户群" model="customergroup">name</modelfields>
				<modelfields name="evaluation" cname="评价体系" model="evaluation">name</modelfields>
				<modelfields name="referGroup" cname="参照客户群" model="customergroup">name</modelfields>
				<field name="referDate" cname="基期" type="date" ></field>
			</input>
		</transaction>
		
	</package>
		
</venus>
