=== jxb8901/uc/venus/web/database.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
数据库配置：
	+数据库：名称、类型、版本、
		+表：名称
				复合表
			+字段
					复合字段
					动态字段
				+字段类型
	+关联：
		数据库间表关联
		
-->

<!ELEMENT databases (database+)>

<!ELEMENT database (table | compositetable | view)+ >
<!ATTLIST database
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	version CDATA #REQUIRED
	ip CDATA #IMPLIED
	port CDATA #IMPLIED
	user CDATA #IMPLIED
	password CDATA #IMPLIED
>

<!ELEMENT table (column+)>
<!ATTLIST table
	name CDATA #REQUIRED	
	alias CDATA #IMPLIED
	centric (true | false) 'false'
>

<!ELEMENT compositetable (table+)>
<!ATTLIST compositetable
	name CDATA #REQUIRED	
	alias CDATA #IMPLIED
	centric (true | false) 'false'
>

<!ELEMENT view (#PCDATA)>
<!ATTLIST view
	name CDATA #REQUIRED
	alias CDATA #IMPLIED
	centric (true | false) 'false'
	table CDATA #REQUIRED
>

<!--
	type: 字段类型
		general: 普通类型
		dyna: 动态字段，目前仅支持日期型动态字段
		formula: 公式字段，即字段是由其它字段通过函数组合而来
		enumer: 枚举字段，字段值为枚举值
-->
<!ELEMENT column (#PCDATA)>
<!ATTLIST column
	name CDATA #REQUIRED	
	alias CDATA #IMPLIED
	sqltype (varchar | date | datetime | time | integer | bigint | autoint | decimal) "varchar"
	len CDATA #IMPLIED
	type (general | dyna ) "general"
	formula CDATA #IMPLIED
	enumer CDATA #IMPLIED
	datecolumn (true | false) "false"
	primarykey (true | false) "false"
	value CDATA #IMPLIED
	asstable CDATA #IMPLIED
	asscolumn CDATA #IMPLIED
>

=== jxb8901/uc/venus/src/database.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE databases PUBLIC 
		"-//ninecube//database1.0//EN" 
		"http://www.ninecube.net/saturn/database.dtd">
<?xml-stylesheet type="text/xsl" href="database.xsl"?>
<databases type="mysql">
	<database name="mysql" type="MySQL" version="5.0" >
		<table name="knc_cust" alias="客户,CUSTOMER,基本客户信息" centric="true">
			<column name="custno" alias="客户号" sqltype="varchar" primarykey="true" />
			<column name="custtp" alias="客户类型" formula="SUBSTRING(custno, 1, 1)" enumer="custtp" />
			<column name="brchno" alias="开户网点" sqltype="varchar" />
			<column name="custna" alias="客户名称,姓名" sqltype="varchar" />
			<column name="ntbkfg" alias="是否开通网银" enumer="yesno.number" />
		</table>
		<table name="knc_prsn" alias="客户,CUSTOMER,个人客户信息" centric="true">
			<column name="custno" alias="ID" sqltype="varchar" primarykey="true" asstable="基本客户信息.客户号" />
			<column name="borndt" alias="出生日期" sqltype="varchar" type="dyna"/>
			<column name="mobitl" alias="移动电话" sqltype="varchar"/>
			<column name="sextp" alias="性别" enumer="sextp" />
		</table>
		<table name="kns_tran" alias="交易,POS消费,POS">
			<column name="transq" alias="交易流水,ID" sqltype="varchar" primarykey="true" />
			<column name="custno" alias="客户号" formula="SUBSTRING(acctno, 1, 10)" asstable="客户.客户号,个人客户信息.ID" />
			<column name="trandt" alias="交易日期,日期,消费日期" sqltype="varchar"  type="dyna" datecolumn="true"/>
			<column name="tranti" alias="交易时间" sqltype="time" />
			<column name="acctno" alias="交易账号" sqltype="varchar" />
			<column name="tranam" alias="金额,交易金额,消费金额" sqltype="decimal" />
			<column name="servtp" alias="交易渠道,交易类型" enumer="servtp" />
			<column name="opertp" alias="操作类型" enumer="opertp" />
			<column name="mrchtp" alias="商户类型" enumer="mrchtp" />
			<column name="trancy" alias="币种" enumer="trancy" />
			<column name="transt" alias="交易状态" enumer="transt" />			
		</table>
	</database>	
	
	<database name="sqlserver" type="SqlServer" version="2000" >
		<table name="POINTCAL" alias="POINTCAL">
			<column name="ID" alias="流水号" sqltype="autoint" primarykey="true" />
			<column name="CUSTOMERID" alias="客户号" sqltype="varchar" asstable="客户.客户号,个人客户信息.ID" />
			<column name="TRANSTYPE" alias="交易类型" sqltype="varchar" />
			<column name="TRANSID" alias="交易流水号" sqltype="varchar" asstable="交易.ID" />
			<column name="POINTTYPE" alias="积分类型" sqltype="varchar" />
			<column name="POINT" alias="积分" sqltype="decimal" />
			<column name="TRANSTIME" alias="积分产生日期" sqltype="date" />
			<column name="COMMENTS" alias="备注信息,COMMENTS" sqltype="varchar" />
			<column name="MARK" alias="标记" sqltype="integer" />
			<column name="PROMOTIONPLANID" alias="营销计划ID" sqltype="bigint" />
		</table>
		
		<table name="POINTJOURNAL" alias="POINTJOURNAL,积分流水">
			<column name="ID" alias="流水号" sqltype="autoint" primarykey="true" />
			<column name="CUSTOMERID" alias="客户号" sqltype="varchar" asstable="客户.客户号,个人客户信息.ID" />
			<column name="TRANSTYPE" alias="交易表名" sqltype="varchar" />
			<column name="TRANSID" alias="交易流水号" sqltype="varchar" asstable="交易.ID" />
			<column name="POINTTYPE" alias="积分类型" sqltype="varchar" />
			<column name="POINT" alias="积分" sqltype="decimal" />
			<column name="TRANSTIME" alias="积分产生日期" sqltype="date"  datecolumn="true" />
			<column name="COMMENTS" alias="备注信息" sqltype="varchar" />
			<column name="PROMOTIONPLANID" alias="营销计划,营销计划ID" sqltype="bigint" />
		</table>

		<table name="TPointType" alias="积分类型">
			<column name="idno" alias="流水号" sqltype="autoint" primarykey="true" />
			<column name="NAME" alias="名称" sqltype="varchar" />
			<column name="DESCRIPTION" alias="描述" sqltype="varchar" />
		</table>

		<table name="POINTACCOUNT" alias="客户积分">
			<column name="ID" alias="流水号" sqltype="autoint" primarykey="true" />
			<column name="CUSTOMERID" alias="客户号" sqltype="varchar" asstable="客户.客户号,个人客户信息.ID"/>
			<column name="POINTTYPE" alias="积分类型" sqltype="varchar" />
			<column name="POINT" alias="积分" sqltype="decimal" />
		</table>
		
		<table name="SMSBONUSCAL" alias="短信奖励Cal,SMSBONUSCAL">
			<column name="ID" alias="流水号" sqltype="autoint" primarykey="true" />
			<column name="CUSTOMERID" alias="客户号" sqltype="varchar" asstable="客户.客户号,个人客户信息.ID"/>
			<column name="CONTENT" alias="内容" sqltype="varchar" />
			<column name="PROMOTIONPLANID" alias="营销计划ID" sqltype="bigint" />
		</table>
		<table name="SMSBONUS" alias="短信奖励,SMSBONUS">
			<column name="ID" alias="流水号" sqltype="autoint" primarykey="true" />
			<column name="CUSTOMERID" alias="客户号"  sqltype="varchar" asstable="客户.客户号,个人客户信息.ID"/>
			<column name="CONTENT" alias="内容" sqltype="varchar" />
			<column name="PROMOTIONPLANID" alias="营销计划ID" sqltype="bigint" />
		</table>
		
	</database>
	
	<database name="formula" type="SqlServer" version="2000" >
		<table name="TMetric" alias="指标表,metric,formula">
			<column name="idno" alias="流水号,idno" primarykey="true" />
			<column name="name" alias="名称,name" sqltype="varchar" />
		</table>
		<table name="MetricValue" alias="指标值表,formulavalues,MetricValue">
			<column name="F_ID" alias="流水号" sqltype="autoint" primarykey="true" />
			<column name="F_Frequence" alias="频度,frequence" sqltype="varchar" />
			<column name="F_Date" alias="日期,date" sqltype="date" />
			<column name="F_TargetType" alias="计算对象类型,target_type" sqltype="varchar" />
			<column name="F_TargetId" alias="计算对象代码,target_id" sqltype="varchar" />
			<column name="F_TargetDataID" alias="计算对象构成元素ID,target_data_id" sqltype="varchar" />
			<column name="F_MetricId" alias="指标,formula_id" sqltype="varchar" />
			<column name="F_DimensionType" alias="维度类型,dimension_type" sqltype="varchar" />
			<column name="F_Dimension" alias="维度,dimension" sqltype="varchar" />
			<column name="F_QuotaValue" alias="指标值,formula_value" sqltype="decimal" />
			<column name="F_Type" alias="生成方式" sqltype="varchar" />
		</table>
	</database>
</databases>

=== jxb8901/uc/venus/web/database.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE databases PUBLIC 
		"-//ninecube//database1.0//EN" 
		"http://www.ninecube.net/saturn/database.dtd">
<?xml-stylesheet type="text/xsl" href="database.xsl"?>
<databases>
	<database name="mysql" type="MySQL" version="5.0" >
		<table name="knc_cust" alias="客户,CUSTOMER,基本客户信息" centric="true">
			<column name="custno" alias="客户号" sqltype="varchar" primarykey="true" />
			<column name="custtp" alias="客户类型" formula="SUBSTRING(custno, 1, 1)" enumer="custtp" />
			<column name="brchno" alias="开户网点" sqltype="varchar" />
			<column name="custna" alias="客户名称,姓名" sqltype="varchar" />
			<column name="ntbkfg" alias="是否开通网银" enumer="yesno.number" />
		</table>
		<table name="knc_prsn" alias="客户,CUSTOMER,个人客户信息" centric="true">
			<column name="custno" alias="ID" sqltype="varchar" primarykey="true" asstable="基本客户信息.客户号" />
			<column name="borndt" alias="出生日期" sqltype="varchar" type="dyna"/>
			<column name="mobitl" alias="移动电话" sqltype="varchar"/>
			<column name="sextp" alias="性别" enumer="sextp" />
		</table>
		<table name="kns_tran" alias="交易,POS消费,POS">
			<column name="transq" alias="交易流水,ID" sqltype="varchar" primarykey="true" />
			<column name="custno" alias="客户号" formula="SUBSTRING(acctno, 1, 10)" asstable="客户.客户号,个人客户信息.ID" />
			<column name="trandt" alias="交易日期,日期,消费日期" sqltype="varchar"  type="dyna" datecolumn="true"/>
			<column name="tranti" alias="交易时间" sqltype="time" />
			<column name="acctno" alias="交易账号" sqltype="varchar" />
			<column name="tranam" alias="金额,交易金额,消费金额" sqltype="decimal" />
			<column name="servtp" alias="交易渠道,交易类型" enumer="servtp" />
			<column name="opertp" alias="操作类型" enumer="opertp" />
			<column name="mrchtp" alias="商户类型" enumer="mrchtp" />
			<column name="trancy" alias="币种" enumer="trancy" />
			<column name="transt" alias="交易状态" enumer="transt" />			
		</table>
		<table name="POINTJOURNAL" alias="POINTJOURNAL,积分流水">
			<column name="ID" alias="流水号" sqltype="autoint" primarykey="true" />
			<column name="CUSTOMERID" alias="客户号" sqltype="varchar" asstable="客户.客户号,个人客户信息.ID" />
			<column name="TRANSTYPE" alias="交易表名" sqltype="varchar" />
			<column name="TRANSID" alias="交易流水号" sqltype="varchar" asstable="交易.ID" />
			<column name="POINTTYPE" alias="积分类型" sqltype="varchar" />
			<column name="POINT" alias="积分" sqltype="decimal" />
			<column name="TRANSTIME" alias="积分产生日期" sqltype="date" />
			<column name="COMMENTS" alias="备注信息" sqltype="varchar" />
			<column name="PROMOTIONPLANID" alias="营销计划,营销计划ID" sqltype="bigint" />
		</table>
		<table name="POINTACCOUNT" alias="客户积分">
			<column name="ID" alias="流水号" sqltype="autoint" primarykey="true" />
			<column name="CUSTOMERID" alias="客户号" sqltype="varchar" asstable="客户.客户号,个人客户信息.ID"/>
			<column name="POINTTYPE" alias="积分类型" sqltype="varchar" />
			<column name="POINT" alias="积分" sqltype="decimal" />
		</table>
		
	</database>
</databases>
